name: Far Cry VR Automated Build

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]

  workflow_dispatch:

jobs:
  build:
    name: Build Far Cry VR
    runs-on: windows-2022

    permissions: write-all

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Python (for meson)
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install meson
        run: pip install meson ninja

      - name: Install Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.0
        with:
          vulkan-query-version: latest
          vulkan-use-cache: true
          vulkan-components: Glslang

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x86

      - name: Prepare MSCV devenv
        uses: bus1/cabuild/action/msdevshell@v1
        with:
          architecture: x86

      - name: Prepare dxvk build
        working-directory: "Sources/ThirdParty/dxvk"
        run: dxvkry_setup.bat

      - name: Build dxvk
        working-directory: "Sources/ThirdParty/dxvk/build"
        run: |
          msbuild dxvk.sln -m
          meson install

      - name: Build CryGame
        working-directory: "Sources/CryGame C++/Solution1"
        run: msbuild Solution1.sln /p:Configuration=Release -m
